--------------------------------------------------------
--  File created - Friday-December-09-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "SYS"."PATIENTS" 
   (	"PATIENTID" NUMBER, 
	"FIRST" VARCHAR2(20 BYTE), 
	"LAST" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" NUMBER, 
	"INSURANCEID" NUMBER, 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"APPOINTMENTID" NUMBER, 
	"DEBT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.PATIENTS
SET DEFINE OFF;
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (11,'Donall','Mummery','dmummery1c@altervista.org',9892466664,409,'05 Hallows Road',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (12,'Cortie','Tyres','ctyres1d@addtoany.com',5664931572,966,'09 2nd Alley',101,44.1);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (13,'Harlen','Chastaing','hchastaing1e@ocn.ne.jp',6534542605,823,'02 Atwood Terrace',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (14,'Shelley','Kinchington','skinchington1f@booking.com',7637889000,867,'6350 Holy Cross Pass',102,82.8);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (15,'Bernarr','Sarre','bsarre1g@theatlantic.com',7685730260,328,'9513 Dahle Lane',103,2.8);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (16,'Yorgo','Fairlem','yfairlem1h@devhub.com',9458143488,825,'91 Green Ridge Crossing',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (17,'Tobit','Crean','tcrean1i@sakura.ne.jp',7021751784,160,'3165 Nova Circle',104,64.6);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (18,'Georgie','Dradey','gdradey1j@disqus.com',9596655812,832,'85401 Marquette Lane',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (19,'Johanna','Vernazza','jvernazza1k@bigcartel.com',1339230916,768,'4513 Barnett Lane',105,3.7);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (20,'Cordula','Quartley','cquartley1l@rakuten.co.jp',4016915181,195,'64110 Straubel Alley',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (21,'Grace','Battill','gbattill1m@theguardian.com',5049139195,940,'821 Tony Pass',106,75.7);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (22,'Michele','Parkman','mparkman1n@timesonline.co.uk',7757251424,387,'9710 Express Place',107,98.1);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (23,'Jessalin','Massimi','jmassimi1o@istockphoto.com',9086295094,737,'26 Atwood Drive',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (24,'Brenda','Baldocci','bbaldocci1p@meetup.com',7071140758,123,'61978 Sullivan Place',108,5);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (25,'Linet','Disdel','ldisdel1q@tripod.com',1765956722,185,'19 Farragut Road',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (26,'Vincent','Stollhofer','vstollhofer1r@ucoz.ru',3128798621,720,'0 Homewood Trail',109,58.5);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (27,'Guthrey','Wolverson','gwolverson1s@yellowbook.com',8253513053,757,'95123 Browning Park',null,0);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (28,'Kirstin','Tuffey','ktuffey1t@angelfire.com',1124784041,629,'6537 Fieldstone Crossing',110,2.8);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (29,'Glenn','McCowen','gmccowen1u@wikia.com',7478971003,955,'9 Lillian Trail',111,7.5);
Insert into SYS.PATIENTS (PATIENTID,FIRST,LAST,EMAIL,PHONE,INSURANCEID,ADDRESS,APPOINTMENTID,DEBT) values (30,'Yard','Powderham','ypowderham1v@bandcamp.com',2955275083,205,'7859 Redwing Plaza',112,97.2);
--------------------------------------------------------
--  DDL for Index PATIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."PATIENTS_PK" ON "SYS"."PATIENTS" ("PATIENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."PATIENTS" MODIFY ("PATIENTID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PATIENTS" ADD CONSTRAINT "PATIENTS_PK" PRIMARY KEY ("PATIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."PATIENTS" ADD CONSTRAINT "PATIENTS_FK1" FOREIGN KEY ("APPOINTMENTID")
	  REFERENCES "SYS"."APPOINTMENTS" ("APPOINTMENTID") ENABLE;
