--------------------------------------------------------
--  File created - Friday-December-09-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRESCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."PRESCRIPTIONS" 
   (	"PRESCRIPTIONID" NUMBER(38,0), 
	"MEDICATIONID" NUMBER(38,0), 
	"PRESCRIPTIONDATE" DATE, 
	"APPOINTMENTID" NUMBER(38,0), 
	"DOSAGE" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.PRESCRIPTIONS
SET DEFINE OFF;
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (999,1009,to_date('05-OCT-22','DD-MON-RR'),101,7);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (844,1007,to_date('03-OCT-22','DD-MON-RR'),102,8);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (998,1003,to_date('02-OCT-22','DD-MON-RR'),103,10);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (231,1002,to_date('11-OCT-22','DD-MON-RR'),104,5);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (157,1005,to_date('04-OCT-22','DD-MON-RR'),105,10);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (425,1010,to_date('11-OCT-22','DD-MON-RR'),106,18);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (616,1001,to_date('06-OCT-22','DD-MON-RR'),107,16);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (320,1008,to_date('13-OCT-22','DD-MON-RR'),108,4);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (627,1004,to_date('08-OCT-22','DD-MON-RR'),109,13);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (569,1001,to_date('12-OCT-22','DD-MON-RR'),110,11);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (861,1006,to_date('07-OCT-22','DD-MON-RR'),111,7);
Insert into SYS.PRESCRIPTIONS (PRESCRIPTIONID,MEDICATIONID,PRESCRIPTIONDATE,APPOINTMENTID,DOSAGE) values (402,1002,to_date('03-OCT-22','DD-MON-RR'),112,19);
--------------------------------------------------------
--  DDL for Index PRESCRIPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."PRESCRIPTION_PK" ON "SYS"."PRESCRIPTIONS" ("PRESCRIPTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."PRESCRIPTIONS" MODIFY ("PRESCRIPTIONID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRESCRIPTIONS" ADD CONSTRAINT "PRESCRIPTION_PK" PRIMARY KEY ("PRESCRIPTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."PRESCRIPTIONS" ADD CONSTRAINT "PRESCRIPTION_FK1" FOREIGN KEY ("MEDICATIONID")
	  REFERENCES "SYS"."MEDICATIONS" ("MEDICATIONID") ENABLE;
